#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${MY_USER} WITH PASSWORD '${MY_PASS}';
  CREATE DATABASE ${MY_DB} OWNER ${MY_USER} TEMPLATE DEFAULT;
  GRANT ALL PRIVILEGES ON DATABASE ${MY_DB} to ${MY_USER};
EOSQL
