- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=dmz

- name: Allow http/https
  command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https

- name: Bounce firewalld
  service: name=firewalld state=restarted

#- name: Disable firewall
#  service: name=firewalld state=stopped
